// Projects/FjerdeSemester/WebApps/AngularApps/MovieInputOutput/src/app/app.component.ts
import { Component } from '@angular/core';
//import { Movie } from './Shared/Movie';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})



export class AppComponent {
  //private selectedMovie: Movie|undefined;

  //public movieSelected(movie: Movie) { this.selectedMovie = movie; }
}

<div class="jumbotron">
  <h1>Angular Movies <img src='assets/Image/movie_img.png'> </h1>
  This small App demonstrates communication between child-components using Input/Output
</div>
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-4">
    <app-movie-list></app-movie-list>
 <!--       <app-movie-list (movie-selected)="movieSelected($event)"> </app-movie-list> -->
  </div>
  <div class="col-sm-5">
<!--           <app-movie-poster [movie]="selectedMovie"> </app-movie-poster> -->
  </div>
  <div class="col-sm-2"></div>
</div>
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-8">
<!--           <app-movie-plot [movie]="selectedMovie"> </app-movie-plot> -->
  </div>
  <div class="col-sm-3"></div>
</div>

// Projects/FjerdeSemester/WebApps/ReactApps/react-toolkit-movie/src/components/App.js
import React, { Component } from 'react';
import MovieImg from '../assets/Image/movie_img.png';
import {MovieList} from './MovieList';
import {MoviePoster} from './MoviePoster';
import {MoviePlot} from './MoviePlot';


class App extends Component {
    
  render() {
    return (
      <div className="App">
        <div className="jumbotron">
          <h1>React-Redux Movies <img alt="Movie" src={MovieImg}></img> </h1>  
           This small React-App demonstrates the use of React-Redux for the communication between child-components
        </div> 
        <div className="row">
          <div className="col-sm-1"></div>
          <div className="col-sm-4">
              <MovieList />
          </div>
          <div className="col-sm-5">
              <MoviePoster />
          </div>
          <div className="col-sm-2"></div>
        </div>
        <div className="row">
          <div className="col-sm-1"></div>
          <div className="col-sm-8">
              <MoviePlot />
          </div>
          <div className="col-sm-3"></div>
        </div>
      </div>
    );
  }
}

export default App;
